# Generated by Django 4.2.1 on 2023-05-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='pics')),
                ('team_name', models.CharField(max_length=250)),
                ('descpn', models.TextField()),
            ],
        ),
    ]
